name: update flake.lock and keydb.cfg
on:
  schedule:
    - cron: "0 0 * * 5"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@0b0e072294b088b73964f1d72dfdac0951439dbd
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: rm flake.lock # ensure a "clean" update
      - run: nix flake update
      - name: commit and push
        run: |
          git config user.name 'GitHub Actions'
          git config user.email 'etc-nixos+github-actions@nyiyui.ca'
          git add flake.lock
          git commit -am "nix flake update"
          rm home-manager/keydb.cfg
          make home-manager/keydb.cfg
          git add home-manager/keydb.cfg
          git commit -am "update home-manager/keydb.cfg"
          git push
